import React,{useState,useEffect} from 'react';
export function Automation({request,notify}){
 const [ai,setAI]=useState(null),[favorite,setFavorite]=useState(null),[reviews,setReviews]=useState([]),[token,setToken]=useState(''),[busy,setBusy]=useState(false);
 const refresh=()=>request('/admin/reviews').then(setReviews).catch(e=>notify(e.message));
 useEffect(()=>{request('/admin/enrichment').then(setAI).catch(e=>notify(e.message));request('/admin/favorites').then(setFavorite).catch(e=>notify(e.message));refresh();},[]);
 async function save(url,value){setBusy(true);try{await request(url,value,'POST');notify('设置已保存');return true;}catch(e){notify(e.message);return false;}finally{setBusy(false);}}
 return <>
 {favorite&&<form className="settings-card" onSubmit={async e=>{e.preventDefault();if(await save('/admin/favorites',favorite))setFavorite(c=>({...c,hasCookie:!!c.cookie||c.hasCookie,cookie:''}));}}><h3>B 站收藏夹自动下载</h3><p>直接监控收藏夹，无需另装 bili-sync。首次同步也会下载已有收藏，每轮最多读取 100 条并继续分页。每首依次下载、整理和分离，系统最多并行处理两项任务。</p><label className="checkbox"><input type="checkbox" checked={favorite.enabled} onChange={e=>setFavorite({...favorite,enabled:e.target.checked})}/>启用自动同步</label><label>收藏夹 ID 或链接<input value={favorite.favoriteId} onChange={e=>setFavorite({...favorite,favoriteId:e.target.value})} placeholder="收藏夹链接中的 fid，不是用户 UID"/></label><label>检查间隔（分钟）<input type="number" min="5" max="1440" value={favorite.intervalMinutes} onChange={e=>setFavorite({...favorite,intervalMinutes:Number(e.target.value)})}/></label><label>B 站 Cookie（可选，用于本人可访问的收藏夹）<input type="password" autoComplete="new-password" value={favorite.cookie||''} placeholder={favorite.hasCookie?'已保存，留空保留':'公开收藏夹可先留空'} onChange={e=>setFavorite({...favorite,cookie:e.target.value})}/></label><div className="modal-actions"><button className="primary" disabled={busy}>保存设置</button><button type="button" disabled={busy} onClick={()=>save('/admin/favorites/sync',{})}>立即同步已保存的收藏夹</button></div></form>}
 {ai&&<form className="settings-card" onSubmit={async e=>{e.preventDefault();if(await save('/admin/enrichment',ai))setAI(c=>({...c,hasKey:!!c.apiKey||c.hasKey,apiKey:''}));}}><h3>AI 歌曲信息识别与刮削</h3><p>发送歌曲标题和现有资料，识别歌手、歌名及标签。支持 OpenAI Responses API；这个密钥不用于音频分离。无法确认的结果进入待核对，人工信息优先。</p><label className="checkbox"><input type="checkbox" checked={ai.enabled} onChange={e=>setAI({...ai,enabled:e.target.checked})}/>下载后自动 AI 整理</label><label>API 地址<input type="url" value={ai.endpoint} onChange={e=>setAI({...ai,endpoint:e.target.value})}/></label><label>模型<input value={ai.model} placeholder="填写支持 Responses 和结构化输出的模型" onChange={e=>setAI({...ai,model:e.target.value})}/></label><label>OpenAI API Key<input type="password" autoComplete="new-password" value={ai.apiKey||''} placeholder={ai.hasKey?'已保存，留空保留':'仅保存在 NAS'} onChange={e=>setAI({...ai,apiKey:e.target.value})}/></label><label className="checkbox"><input type="checkbox" checked={ai.webSearch} onChange={e=>setAI({...ai,webSearch:e.target.checked})}/>联网查证并保存参考来源（模型需支持 web_search，会产生 API 费用）</label><div className="modal-actions"><button className="primary" disabled={busy}>保存设置</button><button type="button" disabled={busy} onClick={()=>save('/admin/enrichment/test',ai)}>测试 AI（调用一次）</button></div></form>}
 <section className="settings-card"><div className="section-heading"><h3>待核对 · {reviews.length}</h3><button onClick={refresh}>刷新</button></div><p>补充歌手和歌名后，自动继续整理入库与音频处理。</p>{reviews.map((r,i)=><form key={r.id} className="review-item" onSubmit={async e=>{e.preventDefault();if(await save('/admin/reviews/'+r.id,r))refresh();}}><p>{r.note}</p><div className="organize-fields"><input aria-label={'核对歌手 '+r.id} value={r.artist} onChange={e=>setReviews(reviews.map((v,n)=>n===i?{...v,artist:e.target.value}:v))}/><input aria-label={'核对歌名 '+r.id} value={r.title} onChange={e=>setReviews(reviews.map((v,n)=>n===i?{...v,title:e.target.value}:v))}/></div><button disabled={busy}>确认并继续</button></form>)}
 <details><summary>企业微信 / Telegram / webhook 管理接口</summary><p>提供独立凭证，只能读取待核对项目、提交歌手与歌名。机器人可调用此接口；平台专用机器人适配器尚未内置。</p><code>GET /api/integrations/reviews</code><br/><code>POST /api/integrations/reviews/:id</code><p>使用 Authorization: Bearer 凭证。不要把凭证放入公开消息或链接。</p><button onClick={()=>request('/admin/integration').then(r=>setToken(r.token)).catch(e=>notify(e.message))}>查看集成凭证</button>{token&&<input aria-label="管理集成凭证" type="password" readOnly value={token} onFocus={e=>e.target.select()}/>}</details></section>
 </>;
}
