import {Automation} from './automation.jsx';
import {tagOptions} from '../shared/tags.js';
import { Organize } from './organize.jsx';
import { Stage } from './stage.jsx';
import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Mic2, Music2, Users, ListMusic, Search, Plus, Monitor, Smartphone, Settings2, ArrowUp, X, Play, Pause, SkipForward, Volume2, QrCode, HardDrive, RefreshCw, ArrowUpRight, Check, Globe2, Radio, ChevronLeft, LogOut, Download, SlidersHorizontal, Disc3 } from 'lucide-react';
import './style.css';
import { Lyrics } from './lyrics.jsx';
import { AISettings } from './settings.jsx';

const modeNames = {instrumental:'纯伴奏',separated:'AI 伴奏',original:'原始音频',tracks:'双音轨',channels:'左右声道'};
const statusNames = {new:'待准备',preparing:'转码中',ready:'可点播',error:'处理失败',queued:'等待中',running:'处理中',done:'已完成',review:'待核对',failed:'失败'};
const route = ['/', '/admin'].includes(location.pathname) ? 'admin' : location.pathname === '/mobile' ? 'mobile' : 'tv';
const fromHash=location.hash.slice(1);
if(fromHash && route==='mobile') {localStorage.setItem('roomToken',fromHash);history.replaceState(null,'',location.pathname);}
let roomToken=localStorage.getItem('roomToken')||'';
let adminToken=sessionStorage.getItem('adminToken')||'';
async function api(url, body, method='GET', isAdmin=false) {
  const response=await fetch('/api'+url,{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${isAdmin?adminToken:roomToken}`},...(body!==undefined?{body:JSON.stringify(body)}:{})});
  const result=await response.json(); if(!response.ok) throw new Error(result.error||'连接失败'); return result;
}
const duration = n => `${Math.floor(n/60)}:${String(Math.floor(n%60)).padStart(2,'0')}`;
function IconButton({icon:Icon,children,...props}) {return <button {...props}><Icon size={19}/>{children}</button>}

function App(){
  const [authenticated,setAuthenticated]=useState(route==='admin'?!!adminToken:!!roomToken);
  const [password,setPassword]=useState(''),[loginBusy,setLoginBusy]=useState(false);
  const [state,setState]=useState({queue:[],playback:{paused:false,vocal:false}}),[songs,setSongs]=useState([]),[artists,setArtists]=useState([]);
  const [tab,setTab]=useState(route==='tv'?'stage':'songs'),[query,setQuery]=useState(''),[artist,setArtist]=useState('');
  const [tag,setTag]=useState('');
  const [join,setJoin]=useState(null),[showQR,setShowQR]=useState(false),[message,setMessage]=useState(''),[connected,setConnected]=useState(false);
  const [reactions,setReactions]=useState([]),[refresh,setRefresh]=useState(0),[admin,setAdmin]=useState(null),[editing,setEditing]=useState(null);
  const [provider,setProvider]=useState('bilibili'),[results,setResults]=useState([]),[searchBusy,setSearchBusy]=useState(false),[onlineUrl,setOnlineUrl]=useState(''),[isBacking,setIsBacking]=useState(false);
  const [name,setName]=useState(localStorage.getItem('guestName')||'家人');
  const current=state.queue[0]||(route==='tv'?state.ambient:null);
  const playback=current?.ambient?{paused:!!current.paused,vocal:true}:state.playback;
  const notify = text => setMessage(text);
  async function attempt(fn,success){try {const value=await fn();if(success)notify(success);return value;}catch(e){notify(e.message);return null;}}
  async function login(e){e.preventDefault();setLoginBusy(true);adminToken=password;const result=await attempt(()=>api('/login',{},'POST',true));if(result){roomToken=result.token;localStorage.setItem('roomToken',roomToken);sessionStorage.setItem('adminToken',adminToken);setAuthenticated(true);}setLoginBusy(false);}
  useEffect(()=>{if(!message)return;const t=setTimeout(()=>setMessage(''),4500);return()=>clearTimeout(t);},[message]);
  useEffect(()=>{
    if(!authenticated)return;
    const events=new EventSource(`/api/events?token=${encodeURIComponent(roomToken)}`);
    events.addEventListener('state',e=>{setState(JSON.parse(e.data));setConnected(true);});
    events.addEventListener('library',()=>setRefresh(n=>n+1));
    events.addEventListener('reaction',e=>{const r=JSON.parse(e.data);setReactions(v=>[...v.slice(-7),r]);setTimeout(()=>setReactions(v=>v.filter(x=>x.id!==r.id)),2400);});
    events.onerror=()=>setConnected(false);
    api('/join?origin='+encodeURIComponent(location.origin)).then(setJoin).catch(e=>notify(e.message));
    return()=>events.close();
  },[authenticated]);
  useEffect(()=>{
    if(!authenticated)return;let alive=true;
    const timer=setTimeout(()=>Promise.all([api(`/songs?q=${encodeURIComponent(query)}&artist=${encodeURIComponent(artist)}&tag=${encodeURIComponent(tag)}`),api('/artists')]).then(([s,a])=>{if(alive){setSongs(s);setArtists(a);}}).catch(e=>notify(e.message)),180);
    return()=>{alive=false;clearTimeout(timer);};
  },[authenticated,query,artist,tag,refresh]);
  useEffect(()=>{if(authenticated&&route==='admin')api('/admin',undefined,'GET',true).then(setAdmin).catch(e=>notify(e.message));},[authenticated,refresh]);
  useEffect(()=>{
    if(route!=='tv')return;
    function key(e){
      document.body.classList.add('keyboard');
      if(e.key==='Escape'||e.key==='BrowserBack'){e.preventDefault();if(showQR)setShowQR(false);else if(artist)setArtist('');else if(tab!=='songs')setTab('songs');else document.querySelector('nav button')?.focus();return;}
      if(!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)||(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName)&&['ArrowLeft','ArrowRight'].includes(e.key))||document.activeElement?.tagName==='SELECT')return;
      const items=[...document.querySelectorAll('button:not(:disabled),input,a[href],select,video')].filter(el=>el.getClientRects().length && !el.closest('[inert]'));
      const active=document.activeElement;
      if(!items.includes(active)){e.preventDefault();items[0]?.focus();return;}
      const rect=active.getBoundingClientRect(),x=rect.x+rect.width/2,y=rect.y+rect.height/2;
      let best,score=Infinity;
      for(const el of items){if(el===active)continue;const r=el.getBoundingClientRect(),dx=r.x+r.width/2-x,dy=r.y+r.height/2-y;
        const main=e.key==='ArrowRight'?dx:e.key==='ArrowLeft'?-dx:e.key==='ArrowDown'?dy:-dy;
        const cross=e.key==='ArrowRight'||e.key==='ArrowLeft'?Math.abs(dy):Math.abs(dx);
        if(main>4&&main+cross*2.5<score){score=main+cross*2.5;best=el;}}
      e.preventDefault();best?.focus();best?.scrollIntoView({block:'nearest'});
    }
    document.addEventListener('keydown',key);const pointer=()=>document.body.classList.remove('keyboard');document.addEventListener('pointerdown',pointer);
    return()=>{document.removeEventListener('keydown',key);document.removeEventListener('pointerdown',pointer);};
  },[tab,artist,showQR]);
  async function control(action){await attempt(()=>api('/control',{action,entryId:current?.id},'POST'));}
  async function add(song){const result=await attempt(()=>api('/queue',{songId:song.id,name},'POST'));if(result)notify(result.preparing?'正在 NAS 预处理，完成后自动加入队列':'已加入点歌队列');}
  async function findOnline(e){e.preventDefault();setSearchBusy(true);setResults([]);const data=await attempt(()=>api(`/online?q=${encodeURIComponent(query)}&provider=${provider}`));if(data)setResults(data);setSearchBusy(false);}
  async function download(v){await attempt(()=>api('/online',{...v,enqueue:true,name,isBacking},'POST'),'已加入下载任务，准备完成后自动加入队列');}
  const logout=()=>{localStorage.removeItem('roomToken');sessionStorage.removeItem('adminToken');location.reload();};

  if(!authenticated)return <div className="login"><div className="login-card"><div className="brandmark"><Mic2/></div><p className="eyebrow">GOOD TIMES, GREAT SONGS</p><h1>好好唱<span>在家，就是主场。</span></h1><p className="muted">{route==='mobile'?'扫描电视上的二维码，即可加入客厅。也可以输入管理密码连接。':'输入 NAS 管理密码，连接你的家庭歌房。'}</p><form onSubmit={login}><label>管理密码<input autoFocus type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="部署时设置的 ADMIN_PASSWORD" required/></label><button className="primary" disabled={loginBusy}>{loginBusy?'正在连接…':'进入好好唱'}<ArrowUpRight size={18}/></button></form><p className="fine">音乐留在 NAS，快乐留在客厅。</p>{message&&<p role="alert" className="error">{message}</p>}</div></div>;

  return <div className={`app ${route} ${tab==='stage'?'stage-home':''}`}>
    <aside className="sidebar"><a className="brand" href={route==='admin'?'/admin':'/tv'}><span className="brandmark"><Mic2 size={23}/></span><span>好好唱<small>HOME KARAOKE</small></span></a><div className="room"><span className={`dot ${connected?'':'offline'}`}/><span>我的客厅<small>{connected?'已连接 · NAS':'正在重新连接…'}</small></span><Radio size={17}/></div><p className="nav-label">{route==='admin'?'管理工作台':'发现你的下一首'}</p><nav>
    {route==='tv'&&<IconButton icon={Play} className={tab==='stage'?'selected':''} onClick={()=>setTab('stage')}>音乐现场</IconButton>}<IconButton icon={Music2} className={tab==='songs'?'selected':''} onClick={()=>{setTab('songs');setArtist('');}}>{route==='admin'?'曲库管理':'歌名点歌'}</IconButton>
    <IconButton icon={Users} className={tab==='artists'?'selected':''} onClick={()=>{setTab('artists');setArtist('');}}>歌星点歌</IconButton>
    <IconButton icon={ListMusic} className={tab==='queue'?'selected':''} onClick={()=>setTab('queue')}>已点歌曲<span className="nav-count">{state.queue.length}</span></IconButton>
    <IconButton icon={Globe2} className={tab==='online'?'selected':''} onClick={()=>setTab('online')}>在线找歌</IconButton>
    {route==='admin'&&<IconButton icon={Settings2} className={tab==='settings'?'selected':''} onClick={()=>setTab('settings')}>设置与任务</IconButton>}
    </nav><div className="sidebar-bottom">{route==='tv'&&join&&<button className="scan-card" onClick={()=>setShowQR(true)}><img src={join.qr} alt="扫码点歌二维码"/><strong>让手机成为点歌台</strong><span>扫码连接当前客厅</span></button>}<div className="endpoint-links"><a href="/tv"><Monitor size={16}/>电视</a><a href="/admin"><Settings2 size={16}/>管理</a><button aria-label="退出" onClick={logout}><LogOut size={16}/></button></div><span className="fine">好好唱 · 把日子唱成歌</span></div></aside>
    <main><header><div className="breadcrumb">我的客厅 <span>/</span> {route==='admin'?'曲库工作台':route==='mobile'?'随身点歌台':'家庭 KTV'}</div><div className="header-right"><span className="connection"><span className={`dot ${connected?'':'offline'}`}/>{connected?'NAS 在线':'连接中'}</span><button className="icon-only" aria-label="扫码点歌" onClick={()=>setShowQR(true)}><QrCode size={20}/></button></div></header>
    <div className="content">{route==='tv'&&tab==='stage'&&<Stage current={current} songs={songs} add={add} choose={()=>setTab('songs')} qr={()=>setShowQR(true)} token={roomToken}/>}
    {tab==='songs'&&!artist&&<section className="hero"><div><p className="eyebrow">YOUR LIVING ROOM. YOUR STAGE.</p><h1>{route==='admin'?'好歌，随时就绪。':'今晚，唱点开心的。'}</h1><p>{route==='admin'?'把收藏整理好，下次相聚只管开唱。':'一首熟悉的旋律，一屋子喜欢的人。'}</p><div className="hero-tags"><span><HardDrive size={14}/>本地优先</span><span><Smartphone size={14}/>扫码点歌</span><span><Volume2 size={14}/>原唱 / 伴奏</span></div></div><div className="record-art" aria-hidden="true"><div className="record"><div className="record-label"><Music2 size={32}/><small>GOOD<br/>TIMES</small></div></div><div className="record-note">SIDE A<br/><strong>一起唱吧</strong><span>33⅓ RPM · HOME SESSION</span></div></div></section>}
    {tab==='songs'&&<><div className="section-heading"><div><h2>{artist|| (route==='admin'?'我的曲库':'从喜欢的歌开始')}<span className="count">{songs.length}</span></h2><p>{artist?'这位歌手的本地歌曲':'歌名、歌手、拼音首字母，都能找到。'}</p></div>{route==='admin'?<><button onClick={()=>setTab('settings')}>整理曲库</button><IconButton icon={RefreshCw} onClick={()=>attempt(()=>api('/admin/scan',{},'POST',true),'已开始扫描媒体目录')}>扫描曲库</IconButton></>:<span className="pill">本地曲库</span>}</div><div className="library-search"><SearchBox query={query} setQuery={setQuery}/><select aria-label="按标签筛选" value={tag} onChange={e=>setTag(e.target.value)}><option value="">全部标签</option>{tagOptions.map(t=><option key={t}>{t}</option>)}</select></div>{artist&&<button className="back" onClick={()=>{setArtist('');setTab('artists');}}><ChevronLeft size={16}/>返回歌手</button>}<div className="song-table"><div className="table-head"><span>歌曲 / 歌手</span><span>音频</span><span>时长</span><span>{route==='admin'?'管理':'点歌'}</span></div>{songs.map((song,i)=><div className="song-row" key={song.id}><div className="song-info"><span className={`song-cover color-${i%5}`}>{song.hasPoster?<img src={'/api/poster/'+song.id+'?token='+encodeURIComponent(roomToken)} alt=""/>:<Music2 size={21}/>}</span><div><strong>{song.title}</strong><small>{song.artist}{!!song.needs_review&&<em> · 待核对</em>}{song.mode==='original'&&<em> · 待分离</em>}{!!song.needs_video&&<em> · 待补视频</em>}{song.status!=='ready'&&<em> · {statusNames[song.status]}</em>}</small></div></div><span className="audio-label">{modeNames[song.mode]}</span><span className="time">{duration(song.duration)}</span>{route==='admin'?<button onClick={()=>setEditing(song)} aria-label={`编辑 ${song.title}`}><SlidersHorizontal size={16}/><span>编辑</span></button>:<button className={state.queue.some(q=>q.song_id===song.id)?'added':'add-song'} disabled={song.status==='preparing'||state.queue.some(q=>q.song_id===song.id)} onClick={()=>add(song)} aria-label={`点歌 ${song.title}`}>{state.queue.some(q=>q.song_id===song.id)?<Check size={19}/>:<Plus size={19}/>}</button>}</div>)}</div>{!songs.length&&<Empty icon={Disc3} title={query?'还没找到这首歌':'把第一首好歌带回家'} text={query?'试试拼音首字母，或去在线找歌。':route==='admin'?'映射 NAS 歌曲目录后，点击「扫描曲库」。':'曲库还没有歌曲，请在 NAS 管理后台扫描并准备歌曲。'} action={<button onClick={()=>route==='admin'?setTab('settings'):setTab('online')}>{route==='admin'?'查看媒体目录':'去在线找歌'}<ArrowUpRight size={16}/></button>}/>}</>}
    {tab==='artists'&&<><div className="section-heading"><div><h1>总有一位，唱进心里。</h1><p>按歌手找到你熟悉的旋律。</p></div><Users size={30}/></div><div className="artist-grid">{artists.map((a,i)=><button className="artist-card" key={a.artist} onClick={()=>{setArtist(a.artist);setQuery('');setTab('songs');}}><div className={`artist-avatar color-${i%5}`}>{a.artist.slice(0,1)}</div><strong>{a.artist}</strong><span>{a.count} 首歌曲</span></button>)}</div>{!artists.length&&<Empty icon={Users} title="歌手们还在路上" text="扫描曲库后，歌手会自动出现在这里。"/>}</>}
    {tab==='queue'&&<><div className="section-heading"><div><h1>好歌，一首接一首。</h1><p>正在播放的歌曲保持在最前，接下来由你安排。</p></div><span className="pill">{state.queue.length} 首已点</span></div>{state.pending?.length>0&&<div className="settings-card"><h3>NAS 正在为你准备</h3>{state.pending.map(j=><p key={j.id}>{j.title} · {statusNames[j.status]}</p>)}<p>准备完成后自动排入队列，当前播放不受影响。</p></div>}<div className="queue-list">{state.queue.map((q,i)=><div className="queue-row" key={q.id}><span className="queue-number">{i===0?<Volume2 size={21}/>:String(i+1).padStart(2,'0')}</span><div><strong>{q.title}</strong><small>{q.artist} · {q.name} 点的</small></div>{i===0?<span className="pill">{state.playback.paused?'已暂停':'当前歌曲'}</span>:<><button aria-label={`置顶 ${q.title}`} onClick={()=>attempt(()=>api(`/queue/${q.id}/top`,{},'POST'))}><ArrowUp size={18}/></button><button aria-label={`移除 ${q.title}`} onClick={()=>attempt(()=>api(`/queue/${q.id}`,undefined,'DELETE'))}><X size={18}/></button></>}</div>)}</div>{!state.queue.length&&<Empty icon={ListMusic} title="舞台已经准备好了" text="点上第一首歌，今晚从你开始。" action={<button className="primary" onClick={()=>setTab('songs')}>去点歌<Plus size={18}/></button>}/>}</>}
    {tab==='online'&&<><div className="section-heading"><div><h1>想唱的歌，再找找。</h1><p>搜索视频，准备好后自动存入曲库并加入队列。</p></div><Globe2 size={30}/></div><form onSubmit={findOnline} className="online-search"><select aria-label="资源平台" value={provider} onChange={e=>setProvider(e.target.value)}><option value="bilibili">Bilibili</option><option value="youtube">YouTube</option></select><SearchBox query={query} setQuery={setQuery}/><button className="primary" disabled={searchBusy||query.length<2}>{searchBusy?'搜索中…':'搜索'}</button></form><label className="checkbox"><input type="checkbox" checked={isBacking} onChange={e=>setIsBacking(e.target.checked)}/>我确认所选资源为纯伴奏，跳过 AI 分离</label><p className="note">在线 MV 可能只有原唱。下载和转码由 NAS 完成，通常需要等待几分钟。</p><form className="url-form" onSubmit={e=>{e.preventDefault();download({url:onlineUrl,title:query||'在线歌曲',artist:provider});}}><input aria-label="视频链接" placeholder="也可以粘贴 Bilibili / YouTube 视频链接" value={onlineUrl} onChange={e=>setOnlineUrl(e.target.value)} type="url" required/><button disabled={!onlineUrl}><Download size={17}/>存入并点歌</button></form><div className="online-results">{results.map(v=><div className="queue-row" key={v.url}><span className="song-cover color-1"><Globe2 size={20}/></span><div><strong>{v.title}</strong><small>{v.artist} · {v.provider}</small></div><button onClick={()=>download(v)}><Plus size={18}/>点歌</button></div>)}</div>{!results.length&&!searchBusy&&<Empty icon={Search} title="让下一首歌，有更多可能" text="输入歌名加「伴奏」或「KTV」，更容易找到适合演唱的版本。"/>}</>}
    {tab==='settings'&&admin&&<><Settings admin={admin} attempt={attempt} refresh={()=>setRefresh(n=>n+1)}/><AISettings attempt={attempt}/></>}
    {route==='mobile'&&<section className="reactions-panel"><h3>给台上的人一点掌声</h3><div>{['👏','🎉','❤️','🌟'].map(emoji=><button aria-label={`发送 ${emoji}`} key={emoji} onClick={()=>attempt(()=>api('/reactions',{emoji},'POST'),'已送到电视大屏')}>{emoji}</button>)}</div><label>怎么称呼你<input value={name} maxLength={24} onChange={e=>{setName(e.target.value);localStorage.setItem('guestName',e.target.value);}}/></label></section>}
    </div></main>
    {route==='tv'&&<Player current={current} playback={playback} notify={notify} reactions={reactions}/>}
    <footer className="player-bar"><div className="now-playing"><div className="mini-record"><Music2 size={18}/></div><div><strong>{current?.title||'下一首，就唱你喜欢的'}</strong><small>{current?`${current.artist} · ${current.ambient?'随机播放 · 原唱':current.mode==='original'?'原唱':playback.vocal?'原唱':'伴奏'}`:'点一首歌，开启今晚的好时光'}</small></div></div><div className="play-controls"><button disabled={!current||current.ambient} onClick={()=>control('vocal')} aria-label="切换原唱伴奏" className={playback.vocal?'active-control':''}><Mic2 size={19}/><span>{current?.mode==='original'?'原始音频':playback.vocal?'原唱':'伴奏'}</span></button><button className="play-toggle" disabled={!current} onClick={()=>control('pause')} aria-label={playback.paused?'播放':'暂停'}>{playback.paused||!current?<Play size={21}/>:<Pause size={21}/>}</button><button disabled={!current} aria-label="切歌" onClick={()=>control('next')}><SkipForward size={21}/><span>切歌</span></button></div><button className="queue-link" onClick={()=>setTab('queue')}><ListMusic size={20}/><span>已点 {state.queue.length}</span></button></footer>
    {showQR&&<Modal title="手机扫码，一起点歌" close={()=>setShowQR(false)}>{join?<div className="join-modal"><img src={join.qr} alt="手机扫码点歌"/><p>手机需能访问下方地址，支持内网或 HTTPS 反代</p><a href={join.url}>{join.url.split('#')[0]}</a><p className="fine">二维码包含客厅访问凭证，请只分享给家人。<br/>外网使用时，在后台设置 HTTPS 反代地址。</p></div>:<p>二维码暂时不可用，请检查 NAS 连接。</p>}</Modal>}
    {editing&&<Editor song={editing} close={()=>setEditing(null)} attempt={attempt} refresh={()=>setRefresh(n=>n+1)}/>}
    {message&&<div className="toast" role="status">{message}</div>}
  </div>;
}

function SearchBox({query,setQuery}){return <div className="search-box"><Search size={20}/><input aria-label="搜索歌名或歌手" placeholder="搜索歌名、歌手或拼音首字母…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button type="button" aria-label="清空搜索" onClick={()=>setQuery('')}><X size={17}/></button>}</div>}
function Empty({icon:Icon,title,text,action}){return <div className="empty"><div className="empty-icon"><Icon size={31}/></div><h3>{title}</h3><p>{text}</p>{action}</div>}
function Modal({title,close,children}){const ref=useRef();useEffect(()=>{const prior=document.activeElement;const dialog=ref.current;dialog.showModal();return()=>{dialog.close();prior?.focus();};},[]);return <dialog ref={ref} onCancel={e=>{e.preventDefault();close();}}><div className="modal-head"><h2>{title}</h2><button aria-label="关闭" onClick={close}><X size={20}/></button></div>{children}</dialog>}
function Settings({admin,attempt,refresh}){const [url,setUrl]=useState(admin.publicUrl),[online,setOnline]=useState(admin.onlineEnabled);return <><div className="section-heading"><div><h1>每一次开唱，都简单。</h1><p>媒体目录、连接方式和后台处理，都在这里。</p></div></div><div className="stats"><div><HardDrive/><strong>{admin.songs}</strong><span>已收录歌曲</span></div><div><Check/><strong>{admin.ready}</strong><span>可立即点播</span></div><div><RefreshCw/><strong>{admin.jobs.filter(j=>['queued','running'].includes(j.status)).length}</strong><span>后台任务</span></div></div><section className="settings-card"><h3>NAS 媒体目录</h3>{admin.roots.map(r=><code key={r}>{r}</code>)}<p>正式曲库需要写入权限以保存整理后的文件，播放缓存保存在数据目录。页面设置会自动保存为 settings.json，重启后继续生效。</p><button onClick={()=>attempt(()=>api('/admin/scan',{},'POST',true),'扫描已加入任务')}><RefreshCw size={17}/>扫描曲库</button></section><Automation request={(url,body,method)=>api(url,body,method,true)} notify={text=>attempt(()=>Promise.resolve(),text)}/><Organize request={(url,body,method)=>api(url,body,method, true)} notify={text=>attempt(()=>Promise.resolve(),text)} refresh={refresh} downloads={admin.downloads} autoImport={admin.autoImport}/><form className="settings-card" onSubmit={async e=>{e.preventDefault();await attempt(()=>api('/admin/settings',{publicUrl:url,onlineEnabled:online},'POST',true),'设置已保存到 settings.json，重新打开电视以更新二维码');refresh();}}><h3>连接与在线资源</h3><label>NAS 访问地址（内网或 HTTPS 反代）<input placeholder="https://ktv.example.com" value={url} onChange={e=>setUrl(e.target.value)} type="url"/></label><p>可填写 http://NAS-IP:3210 或 https://ktv.example.com；留空时二维码跟随当前页面地址。使用独立域名，不要附加 /admin、/tv 等路径。TV APK 填写同一地址，使用管理密码登录。</p><label className="checkbox"><input type="checkbox" checked={online} onChange={e=>setOnline(e.target.checked)}/>启用 Bilibili / YouTube 在线搜索与入库</label><p>仅导入你有权保存和使用的资源。平台限制或网络问题会显示在任务记录中。</p><button className="primary">保存设置</button></form><section className="settings-card"><div className="section-heading"><h3>后台任务</h3><button aria-label="刷新任务" onClick={refresh}><RefreshCw size={17}/></button></div>{admin.jobs.length?admin.jobs.map(j=><div className="job" key={j.id}><div><strong>{{'favorite-sync':'检查收藏夹','favorite-download':'收藏夹下载',enrich:'AI 信息刮削',import:'下载自动入库',scan:'扫描媒体目录',prepare:'准备播放版本',download:'下载在线资源'}[j.kind]}</strong><small>{new Date(j.created).toLocaleString()} · {statusNames[j.status]}</small>{j.error&&<p className="error">{j.error}</p>}</div>{j.status==='failed'&&<button onClick={async()=>{await attempt(()=>api(`/admin/jobs/${j.id}/retry`,{},'POST',true));refresh();}}>重试</button>}</div>):<p>还没有任务。扫描曲库后，就从这里开始。</p>}</section></>}
function Editor({song,close,attempt,refresh}){const [form,setForm]=useState({...song}),[lyrics,setLyrics]=useState(song.lyrics||''),[replacement,setReplacement]=useState(''),[audio,setAudio]=useState(JSON.parse(song.audio||'[]')),[busy,setBusy]=useState(false);const field=(key,value)=>setForm(f=>({...f,[key]:value}));async function save(prepare){setBusy(true);const ok=await attempt(()=>api(`/admin/songs/${song.id}`,form,'PATCH',true));if(ok){await attempt(()=>api(`/admin/songs/${song.id}/lyrics`,{lyrics},'PUT',true));if(prepare)await attempt(()=>api(`/admin/songs/${song.id}/prepare`,{},'POST',true),'已加入转码任务');refresh();close();}setBusy(false);}return <Modal title="歌曲与音频设置" close={close}><div className="editor"><label>歌名<input value={form.title} onChange={e=>field('title',e.target.value)}/></label><label>歌手<input value={form.artist} onChange={e=>field('artist',e.target.value)}/></label><label>资源类型<select value={form.mode} onChange={e=>field('mode',e.target.value)}>{song.mode==='separated'&&<option value="separated">已缓存 AI 伴奏 / 原唱</option>}<option value="original">普通 MV · 原始音频</option><option value="instrumental">纯伴奏 · 无原唱版本</option><option value="tracks">KTV · 独立双音轨</option><option value="channels">KTV · 左右声道</option></select></label><button onClick={async()=>{const info=await attempt(()=>api(`/admin/songs/${song.id}/probe`,{},'POST',true));if(info)setAudio(info.audio);}}>检测媒体音轨</button>{audio.map(a=><p className="fine" key={a.index}>音轨 {a.index} · {a.title} · {a.channels} 声道 · {a.codec}</p>)}{['tracks','channels'].includes(form.mode)&&<div className="two-cols">{[['backing','伴奏'],['vocal','原唱']].map(([key,label])=><label key={key}>{label}{form.mode==='channels'?'声道（0 左 / 1 右）':'音轨序号（从 0 开始）'}<input type="number" min="0" max={form.mode==='channels'?1:31} value={form[key]} onChange={e=>field(key,Number(e.target.value))}/></label>)}</div>}<p className="note">依据实际文件配置。系统不会自动消除普通 MV 的人声；改变音轨配置后需要重新准备。</p>{song.error&&<p className="error">{song.error}</p>}<label>歌词（LRC 或纯文本）<textarea rows="5" value={lyrics} onChange={e=>setLyrics(e.target.value)} placeholder="[00:12.00]第一句歌词"/></label>{!!song.needs_video&&<label>补充视频的容器内路径<input value={replacement} onChange={e=>setReplacement(e.target.value)} placeholder="/media/歌手 - 歌名.mp4"/><button type="button" disabled={!replacement} onClick={async()=>{const ok=await attempt(()=>api(`/admin/songs/${song.id}/replace`,{path:replacement},'POST',true),'视频已补充，请重新检测音轨并准备播放');if(ok){refresh();close();}}}>关联补充视频</button></label>}<div className="modal-actions"><button disabled={busy} onClick={()=>save(false)}>保存</button><button className="primary" disabled={busy} onClick={()=>save(true)}>{busy?'保存中…':'保存并准备播放'}</button></div></div></Modal>}

function Player({current,playback,notify,reactions}){
  const video=useRef(),playerId=useRef(sessionStorage.getItem('playerId')||`tv-${Date.now()}-${Math.random().toString(36).slice(2)}`),position=useRef(0),previousEntry=useRef(null);
  const [time,setTime]=useState(0);
  const [lease,setLease]=useState(false),[blocked,setBlocked]=useState(false),[full,setFull]=useState(false),[error,setError]=useState('');
  const container=useRef();
  const variant=current?.mode==='original'||playback.vocal?'vocal':'backing';
  useEffect(()=>{sessionStorage.setItem('playerId',playerId.current);let alive=true;const beat=()=>api('/player/heartbeat',{id:playerId.current},'POST').then(()=>{if(alive)setLease(true);}).catch(e=>{if(alive){setLease(false);notify(e.message);}});beat();const t=setInterval(beat,5000);return()=>{alive=false;clearInterval(t);};},[]);
  useEffect(()=>{const v=video.current;if(!v||!current||!lease){v?.pause();return;}if(previousEntry.current!==current.id){position.current=0;previousEntry.current=current.id;}else position.current=v.currentTime||position.current;setError('');v.src=`/api/media/${current.song_id}/${variant}?token=${encodeURIComponent(roomToken)}`;v.load();},[current?.id,variant,lease]);
  useEffect(()=>{const v=video.current;if(!v)return;if(playback.paused||!lease)v.pause();else if(current)v.play().then(()=>setBlocked(false)).catch(()=>setBlocked(true));},[playback.paused,current?.id,variant,lease]);
  useEffect(()=>{const handler=()=>setFull(document.fullscreenElement===container.current);document.addEventListener('fullscreenchange',handler);return()=>document.removeEventListener('fullscreenchange',handler);},[]);
  async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await container.current.requestFullscreen();}catch{notify('当前浏览器不支持全屏；APK 会自动横屏显示');}}
  return <section ref={container} className={`tv-player ${full?'is-full':''}`}><div className="video-stage"><video ref={video} playsInline onTimeUpdate={()=>setTime(video.current?.currentTime||0)} onLoadedMetadata={()=>{const v=video.current;v.currentTime=Math.min(position.current,v.duration||0);if(!playback.paused&&lease)v.play().then(()=>setBlocked(false)).catch(()=>setBlocked(true));}} onEnded={()=>{if(current)api('/player/ended',{entryId:current.id,playerId:playerId.current},'POST').catch(e=>notify(e.message));}} onError={()=>{setError('播放失败，请在后台重新准备此歌曲或检查 NAS 连接');}}/>{!!current?.needs_video&&<Lyrics song={current} time={time}/>} {!current&&<div className="stage-empty"><Mic2 size={34}/><span>客厅的舞台，留给你</span></div>}{current&&(blocked||error)&&<div className="video-overlay"><p>{error||'点击播放，开启今晚的第一首'}</p><button onClick={()=>{setError('');video.current?.load();video.current?.play().then(()=>setBlocked(false)).catch(()=>setBlocked(true));}}><Play size={17}/>{error?'重试播放':'开始播放'}</button></div>}<div className="reaction-layer" aria-live="polite">{reactions.map((r,i)=><span key={r.id} style={{left:`${15+i*9}%`}}>{r.emoji}</span>)}</div></div><div className="video-caption"><span><span className={`dot ${lease?'':'offline'}`}/>{current?.ambient?'随机原唱 · '+current.title:current?'正在舞台上':'等待开唱'}</span>{full&&current&&<div className="full-controls">{[['pause',playback.paused?'继续':'暂停'],...(!current.ambient?[['vocal',playback.vocal?'切伴奏':'切原唱']]:[]),['next','切歌']].map(([action,label])=><button key={action} onClick={()=>api('/control',{action,entryId:current.id},'POST').catch(e=>notify(e.message))}>{label}</button>)}</div>}<button onClick={fullscreen} aria-label="全屏播放"><Monitor size={16}/>{full?'退出全屏':'全屏'}</button></div></section>;
}
createRoot(document.getElementById('root')).render(<App/>);
