import React,{useEffect,useState} from 'react';
export function AISettings({attempt}){
  const [config,setConfig]=useState({enabled:false,endpoint:'',model:'',apiKey:'',hasKey:false}),[busy,setBusy]=useState(false);
  async function request(method,body,suffix=''){
    const r=await fetch('/api/admin/ai'+suffix,{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${sessionStorage.getItem('adminToken')}`},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw new Error(data.error);return data;
  }
  useEffect(()=>{attempt(()=>request('GET')).then(v=>{if(v)setConfig({...v,apiKey:''});});},[]);
  const update=(key,value)=>setConfig(c=>({...c,[key]:value}));
  return <form className="settings-card" onSubmit={async e=>{e.preventDefault();setBusy(true);const ok=await attempt(()=>request('POST',config),'AI 分离设置已保存');if(ok)setConfig(c=>({...c,hasKey:!!c.apiKey||c.hasKey,apiKey:''}));setBusy(false);}}><h3>AI 伴奏分离</h3><p>第一次点歌时，NAS 将音频发送到你配置的服务，生成并永久保存伴奏版本。原视频音频保留为原唱。下次直接播放缓存。</p><label className="checkbox"><input type="checkbox" checked={config.enabled} onChange={e=>update('enabled',e.target.checked)}/>启用首次点歌预分离</label><label>分离服务地址<input type="url" value={config.endpoint} placeholder="https://separator.example.com" onChange={e=>update('endpoint',e.target.value)}/></label><label>分离模型<input value={config.model} placeholder="例如 htdemucs（由服务决定）" onChange={e=>update('model',e.target.value)}/></label><label>API Key<input type="password" autoComplete="new-password" value={config.apiKey} placeholder={config.hasKey?'已保存；留空保留原密钥':'可选，取决于服务'} onChange={e=>update('apiKey',e.target.value)}/></label><p>需要 ktv-separation-v1 兼容接口；普通聊天模型 API 不具备音源分离能力。项目附带可自行部署的 Demucs 适配服务，也可接入第三方适配器。启用即允许将点播音频发送至此地址。</p><div className="modal-actions"><button type="button" disabled={busy} onClick={async()=>{setBusy(true);await attempt(()=>request('POST',config,'/test'),'分离服务协议检测通过');setBusy(false);}}>检测服务</button><button className="primary" disabled={busy}>保存配置</button></div></form>;
}
