plugins { id 'com.android.application' }
android {
    namespace 'home.haohaochang.tv'
    compileSdk 36
    defaultConfig {
        applicationId 'home.haohaochang.tv'
        minSdk 23
        targetSdk 28
        versionCode 11
        versionName '0.3.8'
    }
    buildTypes { release { minifyEnabled false } }
}
